### ISSUE TITLE
Generate coverage for integration tests

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#2943]
Codecov can merge multiple reports from our various travis runs.

For this to work, three steps are required:

- [x] Remove cromwell-core dependency from cloud-support #2938 
- [x] Run jes centaur on travis #2948
- [x] Generate coverage for integration tests #2955
