### ISSUE TITLE
Update performance run to use horicromtal

### ISSUE THREAD

**Issue by gemmalam** [broadinstitute/cromwell#4842]
AC: Multiple cromwells are used to execute a performance test.

## Desired Deployment

Utilize single instances for summarizer & reader.  Bring up a instance "group" (a.k.a. cluster) for workers.

### Worker Cromwells [Instance Group](https://cloud.google.com/compute/docs/instance-groups/)

Instantiate a GCP instance group to bring up a cluster of 3 nodes.

### TODO

- [ ] Write an instance template to represent a cromwell worker.
- [ ] Edit Jenkins script to bring up instances as described above.
- [ ] Edit instance startup script to remove shutdown part, move that work to end of Jenkins script.

**Comment by notestaff** [comment]
Currently, does cromwell support the situation where several concurrent cromwell instances share the same MySQL database?  Thanks!

**Comment by notestaff** [comment]
@gemmalam @danbills @mcovarr Sorry to bother you here, but I couldn't get a definite answer on the support forum ( https://gatkforums.broadinstitute.org/wdl/discussion/23421/multiple-cromwell-instances-sharing-the-same-database ).  What is Cromwell's current level of support for multiple cromwell instances sharing the same MySQL database?  From the forum, it seems that it works; but readthedocs don't make it clear, and the existence of the horicromtal label suggests that support for this is still being developed?  Thanks for any info!

**Comment by aednichols** [comment]
Yes, it is still being developed and the first target is a high-throughput Cromwell that is used internally at Broad Institute.

Once we get things working and suitable for end-users we will make it an official, documented feature.

**Comment by gemmalam** [comment]
Moved to Jira and proposed for sprint 3
https://broadworkbench.atlassian.net/browse/BA-4842
